"""posts table

Revision ID: 627ec99b89c0
Revises: 87b9ebe4c3e0
Create Date: 2026-08-27 09:26:09.203444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627ec99b89c0'
down_revision = '87b9ebe4c3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=140), nullable=False))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
