"""users table

Revision ID: 97216d169a0e
Revises: 87b9ebe4c3e0
Create Date: 2026-09-16 21:21:26.951186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97216d169a0e'
down_revision = '87b9ebe4c3e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_post')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_post_recipe_id'), ['recipe_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_recipe_id'))
        batch_op.drop_column('recipe_id')

    op.create_table('_alembic_tmp_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=140), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
